version: "3.8"
services:
  media-huis-sql-server-db:
    container_name: media-huis-sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "s0me_S3cr3t-p@ssw0rd"
      ACCEPT_EULA: "Y"
  media-huis-rabbitmq:
    container_name: media-huis-rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - 15672:15672
      - 5672:5672
  notifcation-api:
    container_name: notifcation-api
    build:
      context: ./notifications
      dockerfile: api.Dockerfile
    image: notification-api:latest
    ports:
      - 5000:80
    depends_on:
      - media-huis-sql-server-db
      - media-huis-rabbitmq
  notifcation-worker:
    container_name: notifcation-worker
    build:
      context: ./notifications
      dockerfile: worker.Dockerfile
    image: notification-worker:latest
    depends_on:
      - media-huis-sql-server-db
      - media-huis-rabbitmq